# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pava_main <- function(y_, nblocks, sidx, size, warmstart) {
    .Call('_simPU_pava_main', PACKAGE = 'simPU', y_, nblocks, sidx, size, warmstart)
}

